security:
  oauth2:
    client:
      clientId: xxxxxxxxxxxxxx
      clientSecret: xxxxxxxxxx
      accessTokenUri: https://www.linkedin.com/oauth/v2/accessToken
      userAuthorizationUri: https://www.linkedin.com/oauth/v2/authorization
      tokenName: access_token
      authenticationScheme: header
      clientAuthenticationScheme: query
    resource:
      userInfoUri: https://api.linkedin.com/v1/people/~?format=json

logging:
  level:
    org.springframework: INFO
...
