security:
  oauth2:
    client:
      clientId: 77hod7nkto9uyp
      clientSecret: 4ZaveyFEmxhaUKl8
      accessTokenUri: https://www.linkedin.com/oauth/v2/accessToken
      userAuthorizationUri: https://www.linkedin.com/oauth/v2/authorization
      tokenName: access_token
      clientAuthenticationScheme: query
    resource:
      userInfoUri: https://api.linkedin.com/v1/people/~?format=json

logging:
  level:
    org.springframework: DEBUG
...
